name: Hata Bildirimi
description: Bir hata veya beklenmeyen davranış bildirin
labels: ["hata", "incelenmeli"]
body:
  - type: markdown
    attributes:
      value: |
        Hata bildirimi için teşekkürler! Lütfen mümkün olduğunca detaylı doldurun.

  - type: textarea
    attributes:
      label: Yeniden Üretme Adımları
      description: Hatayı yeniden oluşturmak için adımları listeleyin.
      placeholder: |
        1. Bir uygulama oluşturun
        2. X butonuna tıklayın
        3. Y hatası oluşuyor
    validations:
      required: true

  - type: textarea
    attributes:
      label: Beklenen ve Gerçekleşen Davranış
      description: Ne olmasını bekliyordunuz ve ne oldu?
      placeholder: "Yukarıdaki adımları takip ettiğimde A olmasını bekliyordum, ancak B gerçekleşti"
    validations:
      required: true

  - type: textarea
    attributes:
      label: Ortam Bilgisi
      description: Lütfen ortam bilgilerinizi paylaşın.
      render: bash
      placeholder: |
        İşletim Sistemi: Ubuntu 22.04
        Mimari: arm64
        Yurt Sürümü: v0.1.0
        VPS Sağlayıcısı: DigitalOcean, Hetzner, vb.
        Dağıtılan uygulama/servis: Veritabanı, Next.js, Laravel, vb.
    validations:
      required: true

  - type: dropdown
    attributes:
      label: Etkilenen alan(lar)
      multiple: true
      options:
        - "Kurulum"
        - "Uygulama"
        - "Veritabanları"
        - "Docker Compose"
        - "Traefik"
        - "Docker"
        - "Uzak Sunucu"
        - "Yerel Geliştirme"
    validations:
      required: true

  - type: textarea
    attributes:
      label: Ek Bilgi
      description: Günlükler, ekran görüntüleri veya yardımcı olabilecek ek bilgiler.

  - type: dropdown
    attributes:
      label: Düzeltmek için PR gönderecek misiniz?
      options:
        - "Evet"
        - "Hayır"
        - "Belki, yardım lazım"
    validations:
      required: true
