blank_issues_enabled: false
contact_links:
  - name: Soru Sorun
    url: https://github.com/karemyazilim/yurt/discussions
    about: Genel sorularınız için GitHub Discussions kullanın.
  - name: Güvenlik Açığı Bildirin
    url: https://github.com/karemyazilim/yurt/security/policy
    about: Güvenlik açıklarını lütfen gizli olarak bildirin.
